name: Gradle Lint

on:
  pull_request:
    paths:
      - .github/workflows/**.yml
      - '*/src/**'
      - gradle/**
      - '**.gradle'
      - gradle.properties
      - gradlew*

jobs:
  AndroidLint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Gradle Lint
        run: ./gradlew lint
        env:
          ORG_GRADLE_PROJECT_githubUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPassword: ${{ github.token }}
      - name: Generate Annotations
        uses: yutailang0119/action-android-lint@v3
        with:
          report-path: '*/build/reports/*.xml'
        if: always()
        continue-on-error: false